### ISSUE TITLE
Inconsistent result

### ISSUE THREAD

**Issue by johngonzalez** [lbm-principles-practice/code#4]
Hi. Thanks for share the code.
When I change nfluids = 1 to nfluids = 2 in **code/chapter9/shanchen.cpp** I get an inconsistent result.

Here the first three outputs:

```
Running time step 0
  Densities: rho_g = 0.1, rho_l = 0.5
  Pressure difference: dp = -0.134382
  Droplet radius: r = 32.75
  Surface tension: gamma = -4.40102

Running time step 100
  Densities: rho_g = nan, rho_l = nan
  Pressure difference: dp = -nan
  Droplet radius: r = 6.93964e-310
  Surface tension: gamma = -nan

Running time step 200
  Densities: rho_g = nan, rho_l = nan
  Pressure difference: dp = -nan
  Droplet radius: r = 6.93964e-310
  Surface tension: gamma = -nan
```
I am going to be thankful for the correction. Thanks

**Comment by shardtor** [comment]
Unfortunately the parameters given in the code result in an unstable calculation when you change the number of components from 1 to 2. Try disabling the self-interaction of component A by setting gA = 0 to get a stable result with two components.
