### ISSUE TITLE
Is it possible to extract physical parameters of a multiphase Shan-Chen simulation? (chapter 9)

### ISSUE THREAD

**Issue by a-rostek** [lbm-principles-practice/code#6]
Hi,

is it possible to extract real physical values from a multiphase simulation which uses Shan-Chen forces? I've been trying to do this with code from chapter 9, but so far with no success.

Also, how does one set a value of G (Shan-Chen force attraction parameter) in a simulation? Is it just trial and error until your simulation matches experiment?

I tried extracting conversion factors between lattice units and physical ones by looking at kinematic viscosity, delta pressure (laplace pressure) and matching them to real substances (for example water). But the derived conversion factors give me ridiculous values when I try to calculate physical density and other quantities.

And now I am questioning whether it's possible at all, since I am not sure if that Shan-Chen parameter G or Shan-Chen equation of state represent anything real.

**Comment by timmkrueger** [comment]
The G parameter has no direct real-world meaning. It is an effective parameter describing the interaction of different fluids (or self-interaction of a single fluid). The usual approach is to change G and "measure" the resulting surface tensions via the Laplace test. The conceptual simplicity of the Shan-Chen model means that you cannot directly map the real world to the simulations and vice versa. There are some more recent papers where more realistic equations of state have been included in the Shan-Chen approach, though.

**Comment by a-rostek** [comment]
Thank you for answering. And thank you for writing this great book :)
